# Generated by Django 4.2.2 on 2023-06-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('fecha', models.DateField()),
                ('sexo', models.BooleanField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=100)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=100)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.sexo')),
            ],
        ),
    ]
